services:
  database:
    container_name: database_ms
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    container_name: php_ms
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/media-stack
    depends_on:
      - database
  nginx:
    container_name: nginx_ms
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/media-stack
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
